name: Proposal
description: Issue template for creating an issue supporting discussion around a project concept or idea.
title: "Proposal: "
labels: ["proposal", "event:PW40_2024_GranCanaria"]
assignees:
  - drouin-simon
  - piiq
  - rafaelpalomar
  - sjh26
  - tkapur

body:
- type: textarea
  attributes:
    label: Project Description
    description: Please provide a brief overview of the project, including the problem it aims to solve, and any expected outcomes.
  validations:
    required: true

